version: '3.8'
services:
  web:
    restart: always
    links:
      - redis
      - database
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./web/.env
  bot:
    restart: always
    links:
      - redis
      - database
    build:
      context: ./
      dockerfile: ./bot/Dockerfile
    env_file:
      - ./bot/.env
  redis:
    image: redis:6-alpine
  database:
    image: mongo:4.4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - ./database/data:/data/db