version: '3.8'
services:
  web:
    restart: always
    network_mode: host
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./web/.env
  bot:
    restart: always
    network_mode: host
    build:
      context: ./
      dockerfile: ./bot/Dockerfile
    env_file:
      - ./bot/.env